# eureka:
#   client:
#     register-with-eureka: true
#     fetch-registry: true
# spring:
#   zipkin:
#     base-url: http://127.0.0.1:9411/

okta:
  oauth2:
    issuer: https://dev-80704293.okta.com/oauth2/default
    audience: api://default

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

spring:
  zipkin:
    baseUrl: http://localhost:9411
